baseURL = "https://macandwen.com/"
languageCode = "en-us"
title = "Mac & Wen"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 24 
googleAnalytics = "UA-48542691-2"
enableRobotsTXT = true
disqusShortname = "macandwen"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  #favicon = "/images/favicon.ico"
  custom_css = ["css/custom.css"]
  description = ""
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/macandwen/"
  youtube = "https://www.youtube.com/channel/UC22DEZV2YfEbcJpUKOB7NOA"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 10

[markup.goldmark.renderer]
  unsafe= true